---
title: "Train Delay Time Prediction"
author: "Tianxiao & Ling"
date: "2023-11-25"
output: html_document
---

# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load package}
library(tidycensus)
library(tidyverse)
library(dplyr)
library(sf)
library(ggplot2)
library(lubridate)
library(tigris)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(RSocrata)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) # plot correlation plot
library(corrr)      # another way to plot correlation plot
library(kableExtra)
library(jtools)     # for regression model plots
library(ggstance) # to support jtools plots
library(ggpubr)    # plotting R^2 value on ggplot point scatter
library(broom.mixed) # needed for effects plots
library(vtable)
library(gganimate)
library(gifski)
library(purrr)
library(geosphere)
library(googlesheets4)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.2),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=10),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#264653","#2a9d8f","#e9c46a",'#f4a261',"#e76f51")
palette4 <- c("#264653","#2a9d8f","#e9c46a","#e76f51")
palette2 <- c("#264653","#2a9d8f")
```

```{r install_census_API_key, warning = FALSE, include=FALSE, eval = TRUE}
# Install Census API Key
tidycensus::census_api_key("acc7865bbb75d743da30b4c1278b0d95cb3062db", overwrite = TRUE, install = TRUE)
```

#Data Wrangling
## NJ Transit Delay Data

```{r}
stop <- st_read("https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Stations/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson") %>%
  mutate(STATION_ID = ifelse(STATION_ID == 'Atlantic City', 'Atlantic City Rail Terminal', STATION_ID),
         STATION_ID = ifelse((STATION_ID == 'Middletown')&(COUNTY == 'Orange,NY'), 'Atlantic City Rail Terminal', STATION_ID),
         STATION_ID = ifelse(STATION_ID == 'Princeton Jct.', 'Princeton Junction', STATION_ID),
         STATION_ID = ifelse(STATION_ID == 'Secaucus Junction Upper Level', 'Secaucus Upper Lvl', STATION_ID),
         line_intersct = str_count(RAIL_SERVICE, ",") + 1)%>%
  dplyr::select(STATION_ID,LATITUDE,LONGITUDE,line_intersct)%>%
  st_drop_geometry()

id <- '1V_kl3QKOxrTlwA8UG7kdv_VpJdaojKMj'
delay_df <- read.csv(sprintf("https://docs.google.com/uc?id=%s&export=download", id))%>%
  filter((type == 'NJ Transit')&(line == 'Northeast Corrdr'))%>%
  na.omit()

merged_dataset <- merge(delay_df, stop, by.x = "from", by.y = "STATION_ID",all.x = TRUE)
merged_dataset <- merge(merged_dataset, stop, by.x = "to", by.y = "STATION_ID",all.x = TRUE)
merged_dataset <- merged_dataset%>%
  rename(from_lat = LATITUDE.x,
         from_lon = LONGITUDE.x,
         from_inter = line_intersct.x,
         to_lat = LATITUDE.y,
         to_lon = LONGITUDE.y,
         to_inter = line_intersct.y
         )%>%
  mutate(distance = distHaversine(cbind(from_lon, from_lat), cbind(to_lon, to_lat)),
         interval60 = floor_date(ymd_hms(scheduled_time), unit = "hour"),
         week = week(interval60),
         dotw = wday(interval60, label=TRUE),
         time_of_day = case_when(hour(interval60) < 7 | hour(interval60) > 18 ~ "Overnight",
                                 hour(interval60) >= 7 & hour(interval60) < 10 ~ "AM Rush",
                                 hour(interval60) >= 10 & hour(interval60) < 15 ~ "Mid-Day",
                                 hour(interval60) >= 15 & hour(interval60) <= 18 ~ "PM Rush"),
         weekend = ifelse(dotw %in% c("周日", "周六"), "Weekend", "Weekday"))
```

## Weather Data
```{r import_weather, warning=FALSE}
weather.Panel <- 
  riem_measures(station = "EWR", date_start = "2019-10-01", date_end = "2019-11-02") %>%
  dplyr::select(valid, tmpf, p01i, sknt)%>%
  replace(is.na(.), 0) %>%
    mutate(interval60 = ymd_h(substr(valid,1,13))) %>%
    mutate(week = week(interval60),
           dotw = wday(interval60, label=TRUE)) %>%
    group_by(interval60) %>%
    summarize(Temperature = max(tmpf),
              Precipitation = sum(p01i),
              Wind_Speed = max(sknt)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))

glimpse(weather.Panel)
```

## Census Data

```{r get_census, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
NJCensus <- 
  get_acs(geography = "county subdivision", 
          variables = c("B01003_001", "B19013_001", 
                        "B02001_002", "B08013_001",
                        "B08012_001", "B08301_001", 
                        "B08301_010", "B01002_001"), 
          year = 2019, 
          state = "NJ", 
          geometry = TRUE, 
          output = "wide") %>%
  rename(Total_Pop =  B01003_001E,
         Med_Inc = B19013_001E,
         Med_Age = B01002_001E,
         White_Pop = B02001_002E,
         Travel_Time = B08013_001E,
         Num_Commuters = B08012_001E,
         Means_of_Transport = B08301_001E,
         Total_Public_Trans = B08301_010E) %>%
  select(Total_Pop, Med_Inc, White_Pop, Travel_Time,
         Means_of_Transport, Total_Public_Trans,
         Med_Age,
         GEOID, geometry) %>%
  mutate(Percent_White = White_Pop / Total_Pop,
         Mean_Commute_Time = Travel_Time / Total_Public_Trans,
         Percent_Taking_Public_Trans = Total_Public_Trans / Means_of_Transport)

NJCensus_select <- NJCensus%>%
  mutate(bigcity = ifelse(Total_Pop >= 6000, 'big city','small city'))%>%
  select(geometry, Total_Pop,bigcity, GEOID)
```

```{r extract_geometries, include=FALSE}
NJTracts <- 
  NJCensus %>%
  as.data.frame() %>%
  distinct(GEOID, .keep_all = TRUE) %>%
  select(GEOID, geometry) %>% 
  st_sf
```

```{r add_census_tracts,warning=FALSE, include=FALSE}
train_census <- st_join(merged_dataset %>% 
          filter(is.na(from_lon) == FALSE &
                   is.na(from_lat) == FALSE &
                   is.na(to_lat) == FALSE &
                   is.na(to_lon) == FALSE) %>%
          st_as_sf(., coords = c("from_lon", "from_lat"), crs = 4326),
        NJTracts %>%
          st_transform(crs=4326),
        join=st_intersects,
              left = TRUE) %>%
  rename(From.Tract = GEOID) %>%
  mutate(from_lon = unlist(map(geometry, 1)),
         from_lat = unlist(map(geometry, 2)))%>%
  as.data.frame() %>%
  select(-geometry)

train_census <- train_census %>%
  st_as_sf(., coords = c("to_lon", "to_lat"), crs = 4326) %>%
  st_join(., NJTracts %>%
            st_transform(crs=4326),
          join=st_intersects,
          left = TRUE) %>%
  rename(To.Tract = GEOID)  %>%
  mutate(to_lon = unlist(map(geometry, 1)),
         to_lat = unlist(map(geometry, 2)))%>%
  as.data.frame() %>%
  select(-geometry)

train_dataset <-train_census  %>%
  left_join(weather.Panel, by ="interval60")

merged_dataset <- train_dataset  %>%
  left_join(NJCensus_select, by = c("From.Tract" = "GEOID")) %>%
  left_join(NJCensus_select, by =c("To.Tract"="GEOID")) %>%
  select(-geometry.x,-geometry.y) %>%
  rename(From_Total_Pop = Total_Pop.x,
         To_Total_Pop = Total_Pop.y,
         From_city = bigcity.x,
         To_city = bigcity.y)
```


```{r plot_weather, fig.height=6, fig.width=8,warning=FALSE}
grid.arrange(
  ggplot(weather.Panel, aes(interval60,Precipitation)) + geom_line(color="#264653") + 
  labs(title="Percipitation", x="Hour", y="Perecipitation") + plotTheme(),
  ggplot(weather.Panel, aes(interval60,Wind_Speed)) + geom_line(color="#264653") + 
    labs(title="Wind Speed", x="Hour", y="Wind Speed") + plotTheme(),
  ggplot(weather.Panel, aes(interval60,Temperature)) + geom_line(color="#264653") + 
    labs(title="Temperature", x="Hour", y="Temperature") + plotTheme(),
  top="Weather Data - NJ EWR - Nov, 2019")
```

```{r delay analysis}
delay_time <- merged_dataset %>%
  group_by(time_of_day)%>%
  summarize(mean_delay = mean(delay_minutes))

delay_day <- merged_dataset %>%
  group_by(dotw)%>%
  summarize(mean_delay = mean(delay_minutes))

delay_week <- merged_dataset %>%
  group_by(weekend)%>%
  summarize(mean_delay = mean(delay_minutes))

delay_hour <- merged_dataset %>%
  group_by(hour(interval60))%>%
  summarize(mean_delay = mean(delay_minutes))

delay_sequence <- merged_dataset %>%
  group_by(stop_sequence)%>%
  summarize(mean_delay = mean(delay_minutes))

delay_distance <- merged_dataset %>%
  group_by(distance)%>%
  summarize(mean_delay = mean(delay_minutes))

delay_intersct_t <- merged_dataset %>%
  group_by(to_inter)%>%
  summarize(mean_delay = mean(delay_minutes))

delay_intersct_f <-merged_dataset %>%
  group_by(from_inter)%>%
  summarize(mean_delay = mean(delay_minutes))

```

```{r map visualization}
map_from <- merged_dataset %>%
  group_by(from)%>%
  summarize(mean_delay = mean(delay_minutes)) %>%
  left_join(stop,by=c('from'='STATION_ID'))%>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326)%>%
  mutate(status = 'from')%>%
  rename(station = from)

map_to <- merged_dataset %>%
  group_by(to)%>%
  summarize(mean_delay = mean(delay_minutes)) %>%
  left_join(stop,by=c('to'='STATION_ID'))%>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326)%>%
  mutate(status = 'to')%>%
  rename(station = to)

ggplot() +
  geom_sf(data = NJTracts, color = 'grey') + 
  geom_sf(data = rbind(map_from,map_to), aes(size = mean_delay,color = mean_delay), alpha = 0.5) +
  scale_colour_viridis(direction = -1,discrete = FALSE, option = "D")+
  scale_size_continuous(name = "Delay Minutes") +
  coord_sf()+
  labs(title="Delayed Time in Station as Start, October, 2019")+
  facet_grid(~status)
  mapTheme()
```

```{r delay analysis combine}
delay_stop_time <- merged_dataset %>%
  group_by(from,to,hour(interval60))%>%
  summarize(mean_delay = mean(delay_minutes))

delay_week_hour <- merged_dataset %>%
  group_by(weekend,hour(interval60))%>%
  summarize(mean_delay = mean(delay_minutes))

delay_intersct_week_f <-merged_dataset %>%
  group_by(from_inter,weekend)%>%
  summarize(mean_delay = mean(delay_minutes))

delay_intersct_week_t <-merged_dataset %>%
  group_by(to_inter,weekend)%>%
  summarize(mean_delay = mean(delay_minutes))

ggplot(delay_week_hour)+
     geom_freqpoly(aes(mean_delay, color = weekend), binwidth = 1)+
  labs(title="Delayed Time in Northeast Corridor - weekend vs weekday, October, 2019",
       x="Hour of the Day", 
       y="Mean Delay time")
```


# Exploratory Analysis
## Serial Autocorrelation - Fixed Effects
## Spatial Autocorrelation - Fixed Effects
## Space-time Autocorrelation
## Operation Effects
## Time Lag Effects
### NE线的每个station前n天delay的lag：lag 1/2/3/4/5/6/7 day
```{r time_lags,include=FALSE}
merged_dataset <- 
  merged_dataset %>% 
  arrange(from_id, interval60) %>% 
  mutate(lagHour = dplyr::lag(delay_minutes,1),
         lag2Hours = dplyr::lag(delay_minutes,2),
         lag3Hours = dplyr::lag(delay_minutes,3),
         lag4Hours = dplyr::lag(delay_minutes,4),
         lag12Hours = dplyr::lag(delay_minutes,12),
         lag1day = dplyr::lag(delay_minutes,24))

```

```{r evaluate_lags, echo=FALSE,warning=FALSE}
as.data.frame(merged_dataset) %>%
    group_by(interval60) %>% 
    summarise_at(vars(starts_with("lag"), "delay_minutes"), mean, na.rm = TRUE) %>%
    gather(Variable, Value, -interval60, -delay_minutes) %>%
    mutate(Variable = factor(Variable, levels=c("lagHour","lag2Hours","lag3Hours","lag4Hours",
                                                "lag12Hours","lag1day")))%>%
    group_by(Variable) %>%  
    summarize(correlation = round(cor(Value, delay_minutes),2))
```

###  NE线上n个station的lag：lag from the previous1/2/3/4/5/…station
```{r station_lags,include=FALSE}
merged_dataset_station <- 
  merged_dataset %>% 
  arrange(train_id, interval60,stop_sequence) %>% 
  mutate(lagsstation = if_else(stop_sequence == 1, 0, lag(delay_minutes, 1)),
         lags2station = if_else(stop_sequence == 1 | stop_sequence == 2, 0, lag(delay_minutes, 2)),
         lags3station = if_else(stop_sequence == 1 | stop_sequence == 2| stop_sequence == 3, 0, lag(delay_minutes, 3)),
         lags4station = if_else(stop_sequence == 1 | stop_sequence == 2| stop_sequence == 3| stop_sequence == 4, 0, lag(delay_minutes, 4)),
         lags5station = if_else(stop_sequence == 1 | stop_sequence == 2| stop_sequence == 3| stop_sequence == 4| stop_sequence == 5, 0, lag(delay_minutes, 5)),
         lags6station = if_else(stop_sequence == 1 | stop_sequence == 2| stop_sequence == 3| stop_sequence == 4| stop_sequence == 5| stop_sequence == 6, 0, lag(delay_minutes, 6)))

```

```{r evaluate_station_lags, echo=FALSE,warning=FALSE}
as.data.frame(merged_dataset_station) %>%
    group_by(train_id) %>% 
    summarise_at(vars(starts_with("lags"), "delay_minutes"), mean, na.rm = TRUE) %>%
    gather(Variable, Value,-train_id,-delay_minutes) %>%
    mutate(Variable = factor(Variable, levels=c("lagsstation","lags2station","lags3station","lags4station",
                                                "lags5station","lags6station")))%>%
    group_by(Variable) %>%  
    summarize(correlation = round(cor(Value, delay_minutes),2))
```